[package]
name = "calc_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "4.0"
calc_core = {path="../calc_core"}

[dependencies.crossterm]
version = "0.24"
features = ["event-stream"]